micronaut:
  application:
    name: productsService

datasources:
  default:
    url: jdbc:postgresql://localhost:5435/products
    username: postgres
    password: password
jpa.default.properties.hibernate.hbm2ddl.auto: update
